# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgA7dyrPJ_-4h8IgINJHXMZZFm09Zvsh
"""



import streamlit as st
import plotly.graph_objects as go
import pandas as pd
from Voyager_Extension import compare_and_visualize

st.set_page_config(page_title="Voyager Optimizer Explorer", layout="wide")

st.title("🧭 Voyager: Optimizer Trajectory Explorer")
st.markdown("""
Explore how different optimizers navigate the high-dimensional **loss landscape** of a neural network.
Each trajectory shows how the optimizer moves through parameter space, projected into 3D using PCA.
""")

# Sidebar inputs
st.sidebar.header("Configuration")
optims = st.sidebar.multiselect(
    "Choose optimizers",
    ["sgd", "adam", "rmsprop"],
    default=["sgd", "adam"]
)

max_steps = st.sidebar.slider("Training Steps", 100, 1000, 300, 50)
steps_per_snapshot = st.sidebar.slider("Steps per Snapshot", 10, 100, 30, 10)

run_button = st.sidebar.button("🚀 Run Experiment")

if run_button:
    with st.spinner("Running comparative analysis... please wait."):
        out = compare_and_visualize(
            optims,
            steps_per_snapshot=steps_per_snapshot,
            max_steps=max_steps,
        )
    st.success("✅ Experiment completed!")

    # Display the 3D trajectory
    st.subheader("3D Optimizer Trajectories")
    st.plotly_chart(out['fig'], use_container_width=True)

    # Metrics comparison
    st.subheader("📊 Comparative Metrics")
    df = pd.DataFrame(out['metrics']).T
    df.index.name = "Optimizer"
    st.dataframe(df.style.format(precision=4))

    # Download option
    csv = df.to_csv().encode("utf-8")
    st.download_button(
        label="💾 Download Metrics as CSV",
        data=csv,
        file_name="optimizer_comparison.csv",
        mime="text/csv",
    )

else:
    st.info("👈 Configure the parameters and click **Run Experiment** to visualize optimizer dynamics.")